### ISSUE TITLE
Error When Downloading Favorites 

### ISSUE THREAD

**Issue by cheese529** [davidkeipert/tikfav#5]
Hey mate, hope you are well! Got this error when trying to download my favorites today, it managed to download 3722 videos before hitting this error, restarting the download did not fix. 
`Downloading video 3722/4746...
getVideo failed Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ECONNRESET'
}`

**Comment by davidkeipert** [comment]
I remember running into this issue a few versions ago. Can't remember what it was but I'm investigating. 

In the meantime it would be helpful if I had the following info from you:

- what operating are you running?
- what version of _Tikfav_ are you using? (Run `tikfav -V`)
- Could you provide the last ~20 lines of output before the error is thrown?

**Comment by cheese529** [comment]
I am running Windows 10, latest version of tikfav, I downloaded the source code, extracted into a new folder and opened that folder with vs code before running the command. Here is the last 20 or so lines
`Getting video metadata for: https://www.tiktokv.com/share/video/7170819082290285867/
Couldn't get data for this URL, video may be deleted
Getting video metadata for: https://www.tiktokv.com/share/video/7173423330043874606/
Downloading video 3709/4746...
Finished downloading video https://www.tiktokv.com/share/video/7173423330043874606/
Getting video metadata for: https://www.tiktokv.com/share/video/7171559998042934534/
Downloading video 3710/4746...
Finished downloading video https://www.tiktokv.com/share/video/7171559998042934534/
Getting video metadata for: https://www.tiktokv.com/share/video/7173855962359483691/
Couldn't get data for this URL, video may be deleted
Getting video metadata for: https://www.tiktokv.com/share/video/7174454018746387754/
Downloading video 3712/4746...
Finished downloading video https://www.tiktokv.com/share/video/7174454018746387754/
Getting video metadata for: https://www.tiktokv.com/share/video/7173842977150897454/
Downloading video 3713/4746...
Finished downloading video https://www.tiktokv.com/share/video/7173842977150897454/
Getting video metadata for: https://www.tiktokv.com/share/video/7174086857897119022/
Downloading video 3714/4746...
Finished downloading video https://www.tiktokv.com/share/video/7174086857897119022/
Getting video metadata for: https://www.tiktokv.com/share/video/7172412449834929451/
Downloading video 3715/4746...
Finished downloading video https://www.tiktokv.com/share/video/7172412449834929451/
Getting video metadata for: https://www.tiktokv.com/share/video/7167131602399677702/
Downloading video 3716/4746...
Finished downloading video https://www.tiktokv.com/share/video/7167131602399677702/
Getting video metadata for: https://www.tiktokv.com/share/video/7168708843415817477/
Downloading video 3717/4746...
Finished downloading video https://www.tiktokv.com/share/video/7168708843415817477/
Getting video metadata for: https://www.tiktokv.com/share/video/7172356614509382918/
Downloading video 3718/4746...
Finished downloading video https://www.tiktokv.com/share/video/7172356614509382918/
Getting video metadata for: https://www.tiktokv.com/share/video/7165946761045953798/
Downloading video 3719/4746...
Finished downloading video https://www.tiktokv.com/share/video/7165946761045953798/
Getting video metadata for: https://www.tiktokv.com/share/video/7173722337534184750/
Downloading video 3720/4746...
Finished downloading video https://www.tiktokv.com/share/video/7173722337534184750/
Getting video metadata for: https://www.tiktokv.com/share/video/7172674769354100014/
Downloading video 3721/4746...
Downloading video 3721/4746...
Finished downloading video https://www.tiktokv.com/share/video/7172674769354100014/
Getting video metadata for: https://www.tiktokv.com/share/video/7173791545936792878/
Downloading video 3722/4746...
getVideo failed Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ECONNRESET'
}`

**Comment by davidkeipert** [comment]
I'm having trouble figuring out what causes that error, but I did improve the error handling so that it will continues downloading videos after that error instead of exiting. 

You can download the [download-fix](https://github.com/davidkeipert/tikfav/tree/download-fix) branch and try running it with the same data file and history file, to see if you can get past that problematic video.

**Comment by cheese529** [comment]
Were you able to reproduce the bug? If not I can help provide steps in reproducing it which may make it easier to figure out what is causing it. 

> it will continue downloading videos after that error instead of exiting.

not sure if this is a good fix because then you'd be losing that video. If the program stops downloading then you know something went wrong which allows you to restart it. What worked for me was deleting the problematic video because it seemed it was corrupted somehow during download and then running the download again fixed it. Had the error again randomly on my second user data file with no corrupted videos(seemed to be fully random) but restarting vscode fixed it so I think restarting the program is the best fix here. The issue seems to happen after running multiple downloads at once.

**Comment by davidkeipert** [comment]
If you can provide any steps to consistently reproduce the bug, that would be helpful because I haven't been able to do it so far. I've tried all sorts of ways to try and trigger it.

Printing a warning, omitting the video from the history file, and continuing with the list is the default behavior for any scenarios where there's no metadata, the video was deleted, etc. So I think that's a change I'll keep.

> but restarting vscode fixed it so I think restarting the program is the best fix here.

Assuming you're using the terminal in VSCode to run `node index.js` there's no reason I can think of why restarting VSCode would impact the node app. Every time you run it you're running a separate process.

**Comment by cheese529** [comment]
You seem to be misunderstanding my man, I am able to trigger it every single time. 
Is there anywhere else we could chat in real time perhaps discord or reddit?
I could better explain and provide screenshots.
My discord is cheesylasagna#6936 and my reddit username is cheesylasagna_ LMK if you end up reaching out, would appreciate it.
