### ISSUE TITLE
video may be deleted

### ISSUE THREAD

**Issue by snowbird00000** [davidkeipert/tikfav#6]
Hiya! Thanks for this tool! However, even with all settings correct, I get the error "video may be removed" with each and every tiktok. I tested the links and they all work. Any idea what the issue could be? Thanks so much!!

EDIT:
I tried other APIs and it seems that titktok has changed the url structure? 
F.i., this is from the user_data.json:
https://www.tiktokv.com/share/video/7259058926543572266/

But most APIs wont work (not sure about this one yet). They will only accept the same video but with this url that tiktok redirects you to when you paste it into a browser;
https://www.tiktok.com/@mind.psy.guidance/video/7259058926543572266

How to solve this?

EDIT 2:
This API works with normal links from the json file:
https://rapidapi.com/liuzhaolong765481/api/tiktok-video-feature-summary/

**Comment by davidkeipert** [comment]
I think I know how to fix this, I'm working on it.

**Comment by davidkeipert** [comment]
still working on this,expect a new release today or tmrw
